name: Ping Website

on:
  schedule:
    - cron: '*/4 * * * *'  # Alle 4 Minuten

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping die Website
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://telbot-7bag.onrender.com/)
          if [ "$STATUS_CODE" -eq 200 ]; then
            echo "Ping erfolgreich! HTTP-Statuscode: $STATUS_CODE"
          else
            echo "Ping fehlgeschlagen! HTTP-Statuscode: $STATUS_CODE"
          fi
